# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: golangci-lint
      name: golangci-lint
      description: Fast linters runner for Go.
      entry: make lint
      types: [go]
      language: golang
      pass_filenames: false
    - id: golang-unittest
      name: golang-unittest
      description: Golang unittest.
      entry: make test
      types: [go]
      language: golang
      pass_filenames: false
